# Generated by Django 4.1.12 on 2024-01-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="sensor.room",
            ),
        ),
    ]
