# Generated by Django 4.1.12 on 2024-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0002_alter_sensor_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=50)),
            ],
        ),
    ]
