# Generated by Django 4.1.12 on 2023-11-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0002_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
