# Generated by Django 4.1.12 on 2023-11-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0003_alter_preferences_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="is_alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sensor",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="sensor.room"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="sensorreading",
            unique_together={("sensor", "time")},
        ),
        migrations.RemoveField(
            model_name="sensorreading",
            name="room",
        ),
    ]
