# Generated by Django 4.1.12 on 2023-11-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0004_sensor_is_active_sensor_is_alive_sensor_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensorreading",
                to="sensor.sensor",
            ),
        ),
    ]
