# Generated by Django 4.1.12 on 2023-11-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sensor", "0005_alter_sensorreading_sensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_reading",
                to="sensor.sensor",
            ),
        ),
    ]
